version: '3'
services:
    postgresqlserver:
        image: postgres:latest
        container_name: kakeibo-sqlserver
        volumes:
           - D:\Docker\Glovo\postgresql:/var/lib/postgresql/data 
        ports:
           - "5432:5432"
        environment:
           - ACCEPT_EULA=Y 
           - MSSQL_PID=postgres
           - POSTGRES_PASSWORD=Postgres2018!

    pgadmin4:
            image: dpage/pgadmin4:latest
            container_name: kakeibo-pgadmin4
            ports:
               - "15432:80"
            environment:
               - PGADMIN_DEFAULT_EMAIL=email@email.com 
               - PGADMIN_DEFAULT_PASSWORD=PgAdmin2018!