# This is a basic workflow to help you get started with Actions

name: Angular

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      working-directory: ./kakeibo-front

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Cachee npm modules 
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          working-directory: ./kakeibo-front
          path: ~/.npm
          key: $ {{ runner.os }}-node-${{ hashFiles('**package-lock.json') }}
          restore-keys: | 
            ${{ runner.os }}-node-
            
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          #working-directory: ${{env.working-directory}}
          node-version: ${{ matrix.node-version }}
      
      - name: npm install and npm run build
        #working-directory: ${{env.working-directory}}
        run: |
          npm install
          npm run build
          
