name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      working-directory: ./API
      run: go build -v main.go
      
    - name: Test
      working-directory: ./API/tests
      run: go test -v
      
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 85.242.73.48
        username: 'guilhermecoelho2@gmail.com'
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          git pull original master
          git status

