name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      working-directory: ./API
      run: go build -v main.go
      
    - name: Test
      working-directory: ./API/tests
      run: go test -v
      
  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.12.12
          with:
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_app_name: "app-guilherme-kakeibo"
                heroku_email: "guilhermecoelho2@gmail.com"
      
